### ISSUE TITLE
Installation in MacOS

### ISSUE THREAD

**Issue by zhumingpassional** [MatProGo-dev/Gurobi.go#3]
I used the new repo you updated, but it still raises errors. My macOS is Monterey 12.6.2

In file Gurobi.go/gurobi/gurobi_passthrough.h, this line is wrong: #include </Library/gurobi1002/mac64/include/gurobi_c.h>

The comments are :
In file included from ../gurobi/env.go:3:
./gurobi_passthrough.h:4:10: fatal error: '/Library/gurobi1002/mac64/include/gurobi_c.h' file not found
#include </Library/gurobi1002/mac64/include/gurobi_c.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Then I changed the path of the gurobi_c.h: revise #include </Library/gurobi1002/mac64/include/gurobi_c.h> to  #include </Library/gurobi1002/macos_universal2/include/gurobi_c.h>
It is still wrong, and the comments are:
github.com/MatProGo-dev/Gurobi.go/examples
/Users/mingzhu/go/go1.21rc3/pkg/tool/darwin_amd64/link: running clang failed: exit status 1
ld: warning: directory not found for option '-L/Library/gurobi1002/mac64/lib'
ld: library not found for -lgurobi_c++
clang: error: linker command failed with exit code 1 (use -v to see invocation)

'-L/Library/gurobi1002/mac64/lib' does not exit in my Mac, which is /Library/gurobi1002/macos_universal2/lib

I reivsed #include </Library/gurobi1002/mac64/include/gurobi_c.h> to 
#include </Library/gurobi1002/macos_universal2/include/gurobi_c.h>
and  // #cgo LDFLAGS: -L/Library/gurobi1002/mac64/lib -lgurobi_c++ -lgurobi100 to
// #cgo LDFLAGS: -L/Library/gurobi1002/macos_universal2/lib -lgurobi_c++ -lgurobi100
it works.

thanks again for your works.

**Comment by kwesiRutledge** [comment]
(I'm tagging your first issue, #1, for the sake of keeping things together. )

**Comment by zhumingpassional** [comment]
can I submit a PR?

**Comment by kwesiRutledge** [comment]
> could you please update it again? If it is related to different OS versions, I hope you can provide the interface and let users select it.

It looks like this is not an issue with different OS's, but rather a change that Gurobi made in how they install the program on all Mac OS X computers. It looks like it used to be installed into a directory `/Library/gurobiXXX/mac64`, but they recently renamed that directory on the Mac installation. Thanks for pointing this out!

I will try to fix this later on tomorrow, when I get a free moment.

**Comment by kwesiRutledge** [comment]
Of course! I think I see what needs to be changed as well, but feel free to send one if you see what needs to change.

**Comment by zhumingpassional** [comment]
but when I submit PR, it raise error:
remote: Permission to MatProGo-dev/Gurobi.go.git denied to zhumingpassional.
fatal: unable to access 'https://github.com/MatProGo-dev/Gurobi.go.git/': The requested URL returned error: 403

can you open it for me?

**Comment by kwesiRutledge** [comment]
It sounds like you are pushing directly to the main repository. Can you create a fork and then try to make the pull request using your fork, instead?

We aim to use that standard on this Go project.

**Comment by zhumingpassional** [comment]
I created a new branch:
![image](https://github.com/MatProGo-dev/Gurobi.go/assets/43677883/de0ed6ee-4448-444a-be58-87fa07452e34)

I do not know the reason

**Comment by kwesiRutledge** [comment]
A new change has been pushed to the main branch which might help with your problem.

> I do not know the reason.

You do not know the reason why you created the branch? Oh! This is part of one of the "habits" that GitHub users use for organizing how they make changes to public projects/repositories. You can read more about this [here](https://jarv.is/notes/how-to-pull-request-fork-github/).

If you've never done this before, then that can be a good thing to keep in mind for future projects! :)

**Comment by zhumingpassional** [comment]
I know the reason.
I did it as the instructions of git.
but it still failed.

 I created a new branch revise_gurobi_path, and pushed it.
git push --set-upstream origin revise_gurobi_path

remote: Permission to MatProGo-dev/Gurobi.go.git denied to zhumingpassional.
fatal: unable to access 'https://github.com/MatProGo-dev/Gurobi.go.git/': The requested URL returned error: 403

**Comment by zhumingpassional** [comment]
I really failed in pushing the PR on my branch.

I WILL send the revised files to you  and you can update the repo. can you tell me your email?

**Comment by kwesiRutledge** [comment]
Sure, you can send me the files, but you don't need my email to do it; you can attach the files in this thread and GitHub will make sure it goes to my email.

**Comment by kwesiRutledge** [comment]
And have you tried the most recent version of the tool (commit 2845f33)?

**Comment by zhumingpassional** [comment]
I revised the two files as：

https://github.com/zhumingpassional/my_gurobi.go/blob/master/gurobi/gurobi_passthrough.h

https://github.com/zhumingpassional/my_gurobi.go/blob/master/gurobi/cgoHelper.go

**Comment by zhumingpassional** [comment]
I tried to attach. but failed.

![image](https://github.com/MatProGo-dev/Gurobi.go/assets/43677883/14aad5f0-9da6-43e6-93bf-d21d1a9fc6a5)

so I send you the website of files.

**Comment by kwesiRutledge** [comment]
Thank you for your help with this! I will include this in upcoming updates which will make this Go module more useful for future programmers. I'll link this issue to a future pull request and will close it now that you have found a solution!
